### ISSUE TITLE
'main' panicked at 'removal of null terminator' with data from README and Linux client

### ISSUE THREAD

**Issue by mindtechmedia** [wilsonzlin/edgesearch#5]
Using the Linux binary client and the data from the README I am getting the following error and I have no idea what I am doing wrong.

Any help would be appricated :)

documents.txt
```
{"title":"Stupid Love","artist":"Lady Gaga","year":2020} \0
{"title":"Don't Start Now","artist":"Dua Lipa","year":2020} \0
```

document-terms.txt:
```
title_stupid \0 title_love \0 artist_lady \0 artist_gaga \0 year_2020 \0 \0
title_dont \0 title_start \0 title_now \0 artist_dua \0 artist_lipa \0 year_2020 \0 \0
```

```
RUST_BACKTRACE=full  ./edgesearch   --documents documents.txt   --document-terms document-terms.txt   --maximum-query-results 20   --output-dir dist/worker/
```

```
thread 'main' panicked at 'removal of null terminator', src/data/document_terms.rs:56:21
stack backtrace:
   0:     0x564f916dcdf4 - backtrace::backtrace::libunwind::trace::hc1c4a1d8ad423b97
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x564f916dcdf4 - backtrace::backtrace::trace_unsynchronized::h82274781060cb056
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x564f916dcdf4 - std::sys_common::backtrace::_print_fmt::h2a45d89b653a4da8
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x564f916dcdf4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41a0a93ab85e6aa1
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x564f91706c5c - core::fmt::write::hdaea18585065a96d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x564f916da953 - std::io::Write::write_fmt::h0cea70c809005252
                               at src/libstd/io/mod.rs:1504
   6:     0x564f916df945 - std::sys_common::backtrace::_print::hd95f9978cc145ca4
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x564f916df945 - std::sys_common::backtrace::print::hfb25ca2291be47d0
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x564f916df945 - std::panicking::default_hook::{{closure}}::h44f76cee5dc8591c
                               at src/libstd/panicking.rs:198
   9:     0x564f916df682 - std::panicking::default_hook::h198e1a712910f1e6
                               at src/libstd/panicking.rs:218
  10:     0x564f916dffa2 - std::panicking::rust_panic_with_hook::hc0b4730bb8013f9d
                               at src/libstd/panicking.rs:511
  11:     0x564f916dfb8b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x564f91705681 - core::panicking::panic_fmt::h1ac71ad045d55416
                               at src/libcore/panicking.rs:111
  13:     0x564f91705413 - core::option::expect_failed::h7baa1c60813ff0e3
                               at src/libcore/option.rs:1260
  14:     0x564f91675228 - <edgesearch::data::document_terms::DocumentTermsReader as core::iter::traits::iterator::Iterator>::next::hd8425f88ccfdcc36
  15:     0x564f9166f584 - edgesearch::build::build::h38305df836e7a53a
  16:     0x564f9166e506 - edgesearch::main::h0cc1efdc0569d412
  17:     0x564f9166ecf3 - std::rt::lang_start::{{closure}}::h052b2793b163c52a
  18:     0x564f916e03e8 - std::rt::lang_start_internal::{{closure}}::h7a212202ff76034b
                               at src/libstd/rt.rs:52
  19:     0x564f916e03e8 - std::panicking::try::do_call::h6d214a73427d759b
                               at src/libstd/panicking.rs:331
  20:     0x564f916e03e8 - std::panicking::try::hc078f0e11721d1cb
                               at src/libstd/panicking.rs:274
  21:     0x564f916e03e8 - std::panic::catch_unwind::hb31c05be30625612
                               at src/libstd/panic.rs:394
  22:     0x564f916e03e8 - std::rt::lang_start_internal::hcf7fb98a775d5af0
                               at src/libstd/rt.rs:51
  23:     0x564f9166e8d2 - main
  24:     0x7f96ecf35cb2 - __libc_start_main
  25:     0x564f91669c9a - _start
  26:                0x0 - <unknown>
```

**Comment by MantraMedia** [comment]
Updating the code to use a different separator than `\0` worked

**Comment by mindtechmedia** [comment]
Updating the code to use a different separator worked

**Comment by wilsonzlin** [comment]
Originally did you use a null terminator (ASCII 0) or the literal string `\0`? In the README sample data, `\0` represents the U+0000 character, not a literal backslash followed by a zero. Also note that there is no space around entries or `\0`; it's a binary data format (admittedly should not have used `.txt` as the sample file name, will change this).

**Comment by mindtechmedia** [comment]
Yes, as it was a .txt file I understood it as the literal string :)

**Comment by AnshBansh** [comment]
Could you please share sample document and documentterm files
