### ISSUE TITLE
Issue compiling worker

### ISSUE THREAD

**Issue by coughlanio** [wilsonzlin/edgesearch#7]
*Update*: Turns out this was due to not having clang, lld or wasm-ld. Installing v11 of each seems to have resolved my issue!

```rust
Reading document terms (94.02%)...
Processing documents (0%)...
Processing documents (18.42%)...
Processing documents (36.85%)...
Processing documents (55.27%)...
Processing documents (73.7%)...
Processing documents (92.12%)...
There are 11,116 documents with 15,900 terms
1 chunks contain terms
1 chunks contain documents
thread 'main' panicked at 'compile WASM: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/build/wasm.rs:102:22
stack backtrace:
   0:     0x5569e3143e20 - std::backtrace_rs::backtrace::libunwind::trace::h04d12fdcddff82aa
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x5569e3143e20 - std::backtrace_rs::backtrace::trace_unsynchronized::h1459b974b6fbe5e1
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5569e3143e20 - std::sys_common::backtrace::_print_fmt::h9b8396a669123d95
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5569e3143e20 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he009dcaaa75eed60
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5569e31684cc - core::fmt::write::h77b4746b0dea1dd3
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
   5:     0x5569e3141002 - std::io::Write::write_fmt::heb7e50902e98831c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
   6:     0x5569e3146585 - std::sys_common::backtrace::_print::h2d880c9e69a21be9
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5569e3146585 - std::sys_common::backtrace::print::h5f02b1bb49f36879
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5569e3146585 - std::panicking::default_hook::{{closure}}::h658e288a7a809b29
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
   9:     0x5569e3146228 - std::panicking::default_hook::hb52d73f0da9a4bb8
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
  10:     0x5569e3146d21 - std::panicking::rust_panic_with_hook::hfe7e1c684e3e6462
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
  11:     0x5569e3146867 - std::panicking::begin_panic_handler::{{closure}}::h42939e004b32765c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
  12:     0x5569e31442dc - std::sys_common::backtrace::__rust_end_short_backtrace::h9d2070f7bf9fd56c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5569e31467c9 - rust_begin_unwind
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
  14:     0x5569e3166e31 - core::panicking::panic_fmt::ha0bb065d9a260792
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
  15:     0x5569e3166c53 - core::option::expect_none_failed::h7e1dd0a94971eb61
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
  16:     0x5569e30d1008 - edgesearch::build::wasm::generate_and_compile_runner_wasm::he796daae589dc04c
  17:     0x5569e30cc5dc - edgesearch::build::build::hf79fefb20336bfa3
  18:     0x5569e30c7a9b - edgesearch::main::heb516d46d23f0e37
  19:     0x5569e30c4b33 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3c4b2ea8815b4622
  20:     0x5569e30c4b09 - std::rt::lang_start::{{closure}}::h005a553ef7350dea
  21:     0x5569e3147147 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h57e2a071d427b24c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259:13
  22:     0x5569e3147147 - std::panicking::try::do_call::h81cbbe0c3b30a28e
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
  23:     0x5569e3147147 - std::panicking::try::hbeeb95b4e1f0a876
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
  24:     0x5569e3147147 - std::panic::catch_unwind::h59c48ccb40a0bf20
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
  25:     0x5569e3147147 - std::rt::lang_start_internal::ha53ab63f88fee728
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51:25
  26:     0x5569e30c7f12 - main
  27:     0x7ff7c883809b - __libc_start_main
  28:     0x5569e30c47ba - _start
  29:                0x0 - <unknown>
```

**Comment by coughlanio** [comment]
I'm also seeing the same issue with the included Microsoft demo:

```rust
➜  build git:(master) ✗ ./edgesearch --documents docs.txt --document-terms terms.txt --output-dir output --data-store KV
Reading document terms (28.09%)...
Processing documents (0%)...
Processing documents (16.31%)...
Processing documents (32.63%)...
Processing documents (48.94%)...
Processing documents (65.25%)...
Processing documents (81.57%)...
Processing documents (97.88%)...
There are 6,277 documents with 34,429 terms
1 chunks contain terms
1 chunks contain documents
thread 'main' panicked at 'compile WASM: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/build/wasm.rs:102:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by coughlanio** [comment]
So had a little dig in the code, and figured out my issue was not having `clang`, `lld` or `wasm-ld`. Installing v11 of each seems to have resolved my issue!
